"""
Step 3: The sandbox.

Takes the code string generated by agent/core.py, executes it against
a real DataFrame, and returns either:
    - a success result, or
    - the exact error message/traceback, so Step 4 (RAG self-correction)
      can use it to fix the code.

This is intentionally a *restricted* exec environment: the generated
code only gets access to pandas, numpy, and the DataFrame itself.
No file system, no network, no other imports.
"""

import traceback
import pandas as pd
import numpy as np


def run_generated_code(code: str, df: pd.DataFrame) -> dict:
    """
    Executes `code` (which must define an `analyze(df)` function),
    then calls analyze(df) and returns the outcome.

    Returns a dict:
        {"success": True, "result": {...}}
        or
        {"success": False, "error": "traceback text"}
    """
    # Restricted namespace: only pandas and numpy are available inside
    # the generated code, nothing else (no os, no open(), no imports).
    safe_globals = {
        "pd": pd,
        "np": np,
        "__builtins__": {
            "range": range,
            "len": len,
            "sum": sum,
            "min": min,
            "max": max,
            "sorted": sorted,
            "list": list,
            "dict": dict,
            "str": str,
            "int": int,
            "float": float,
            "bool": bool,
            "abs": abs,
            "round": round,
            "enumerate": enumerate,
            "zip": zip,
        },
    }
    local_namespace = {}

    try:
        # Step A: define the analyze() function from the generated code
        exec(code, safe_globals, local_namespace)

        if "analyze" not in local_namespace:
            return {
                "success": False,
                "error": "Generated code did not define a function named 'analyze'.",
            }

        # Step B: actually call it with the real dataframe
        analyze_fn = local_namespace["analyze"]
        result = analyze_fn(df)

        return {"success": True, "result": result}

    except Exception:
        # Capture the FULL traceback text — this is what gets handed to
        # the RAG self-correction step so the agent can see exactly
        # what went wrong (e.g. KeyError: 'Region' vs actual column 'region').
        return {"success": False, "error": traceback.format_exc()}


if __name__ == "__main__":
    # Quick manual test: reuse the exact code Gemini generated in Step 2
    sample_df = pd.DataFrame({
        "region": ["North", "South", "East", "West", "North", "South"],
        "sales": [1200, 950, 1100, 800, 1300, 1000],
    })

    good_code = """
def analyze(df):
    region_sales = df.groupby('region')['sales'].sum()
    highest_sales_region = region_sales.idxmax()
    return {
        "result": highest_sales_region,
        "chart_type": "bar",
        "chart_data": region_sales.sort_values(ascending=False)
    }
"""

    bad_code = """
def analyze(df):
    # deliberately wrong column name to test error capture
    region_sales = df.groupby('Region')['sales'].sum()
    return {"result": region_sales.idxmax(), "chart_type": "bar", "chart_data": region_sales}
"""

    print("\n--- Running GOOD code ---")
    print(run_generated_code(good_code, sample_df))

    print("\n--- Running BAD code (on purpose) ---")
    print(run_generated_code(bad_code, sample_df))